# Generated by Django 3.1.7 on 2021-09-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210908_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='anime_plot',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
