# Generated by Django 3.1.7 on 2021-09-08 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0015_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=2000)),
                ('rate', models.PositiveSmallIntegerField(choices=[(1, '1 - Horrible'), (2, '2 - Bad'), (3, '3 - OK'), (4, '4 - Good'), (5, '5 - Master Piece')])),
            ],
        ),
        migrations.AlterField(
            model_name='anime',
            name='anime_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.AddField(
            model_name='reviews',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.anime'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
